sudo: false
language: node_js

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x

node_js:
  - "6"
  - "4"

before_script:
  - npm uninstall seneca
  - npm install seneca$SENECA_VER
  - echo FLAGS:$LAB_FLAGS

after_script:
  - npm run coveralls
